### ISSUE TITLE
Fields are black-on-black on Firefox w/ dark theme

### ISSUE THREAD

**Issue by JakeMerdichAMD** [fregante/webext-base-css#6]
Text in any textbox is black-on-black with any dark theme. This makes it nearly impossible to actually use the options page.

![image](https://user-images.githubusercontent.com/60545770/122281615-72303b80-ceb8-11eb-8d4d-83f557547b3a.png)

**Comment by fregante** [comment]
What OS, browser and theme are you using? That’s not how it looks normally

**Comment by JakeMerdichAMD** [comment]
Win10 20H2, Firefox 89.0.1, and official 'Dark' theme. Also repros with other dark themes like 'Arc Dark Theme', so if it's a theme issue, it's not just a bug on a single theme. Haven't tried different OSs or a clean profile yet.

**Comment by JakeMerdichAMD** [comment]
Found a key thing to repro: the windows "default app mode" has to be light to repro this (settings->personalization->colors->Choose you default app mode). Setting the default app mode to dark makes this issue go away.

**Comment by cheap-glitch** [comment]
Seeing this too:
![image](https://user-images.githubusercontent.com/46634000/124310627-bedc6d80-db6c-11eb-9995-31bdf99cc0b2.png)

Firefox with dark theme, running on Arch Linux with the default GTK theme (Adwaita). :point_right: I think the problem comes from using a dark skin for the Firefox UI, while having a "bright" desktop theme enabled.

**Comment by fregante** [comment]
This likely because I load the Firefox’ theme directly and it affects the fields only partially. I need to see if there's some class that should be added to the form to catch more styles.
